#!/usr/bin/env node
/**
 * verify.js — runs every gate against the app in one command.
 *
 *   node audit/verify.js path/to/layi_dashboard.html
 *   node audit/verify.js                 # defaults to ./site/layi_dashboard.html
 *
 * Exit code 0 = all gates green. Non-zero = at least one gate failed.
 * Run this BEFORE and AFTER any change. A change that turns a gate red is a regression.
 */
const { execFileSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const app = path.resolve(process.argv[2] || 'site/layi_dashboard.html');
if (!fs.existsSync(app)) { console.error('Cannot find app file: ' + app); process.exit(2); }
const here = __dirname;

const GATES = [
  ['parsecheck.js',       'Parse            ', 'Every inline <script> block parses. Catches the #1 hazard: a straight apostrophe inside a single-quoted JS string.'],
  ['smoke_dash_fixes.js', 'Runtime smoke    ', 'Loads the app in a stubbed DOM, seeds demo data, and calls every dashboard drill function for real.'],
  ['check_sync.js',       'Figure sync      ', 'A KPI card and its drill-down must total the SAME period + branch. This is the bug class that caused "₦1.8m on the card, ₦0 in the popup".'],
  ['audit_branches.js',   'Branch parity    ', 'Renders the dashboard for EVERY studio; fails if any card jumps to a tab instead of opening a breakdown, or shows another branch\'s data.'],
  ['audit_roles.js',      'Role parity      ', 'Renders every role\'s dashboard (owner/manager/accountant/CRE/tailor/assistant) on every studio. Fails on tab-jumps, stale appointment forms, wrong finance exposure, dead Orders cards.'],
  ['audit_perms.js',      'Permission matrix', 'Asserts each role\'s exact access, that NEW permissions fall back to old behaviour (no regressions for existing accounts), and that toggling one permission does not bleed into others.'],
  ['audit_cards.js',      'Dead-card sweep  ', 'Renders every tab for every role on every studio; fails if any KPI stat card has no drill-down.'],
  ['audit_reporting.js',  'Reporting lines  ', 'Fails on a self-report, a reporting loop, or a manager pointing at a deleted staff member; verifies the guards catch each and that leaving reassigns reports up the chain.'],
  ['audit_branch_staff.js','Branch staff scope', 'Fails if a single-branch view lists a staff member from another studio, or if the branch switcher has no "All studios" option.'],
  ['audit_branch_labels.js','Branch row labels ', 'In the All-studios view every list row must show which studio it belongs to; in a single-branch view it must not.'],
  ['audit_branch_scope.js', 'Branch scope     ', 'Every branch-owned record appears in exactly ONE studio, never none and never two; anything that cannot be placed is reported to the owner on the Branches page rather than quietly hidden. Company records reach every studio unless they name the ones they apply to. The catalogue is the label’s while the stock on the shelves is each studio’s, a sale draws only from the studio that made it, and a rename carries records and stock across. Every tab must declare its scope in VIEW_SCOPE, so a new screen cannot ship without deciding what it shows.'],
  ['audit_accounts.js',    'Account ↔ staff  ', 'The New Account form offers to create a matching staff record when none is linked; accepting creates it one-to-one, declining shows a "no linked staff" hint, and a staff record links to at most one account.'],
  ['audit_period.js',      'Period response  ', 'The dashboard finance KPI cards must track the period/calendar selector and their drills must total the same period; Outstanding must stay an all-orders snapshot.'],
  ['audit_console_pages.js','Console renders  ', 'Loads the console the way the browser does, hands it the rows admin-api really returns, renders the pages and reads the HTML back. The previous gate checked the console CALLS the tenants action; it did, and the page still said "No subscribers match this filter" because the console pinned its own idea of today to a date in the past, so every period filter ended before any real studio had joined. Present in the data, invisible on every page.'],
  ['audit_console_live.js', 'Console gateway  ', 'Every action admin-api serves for an owner is either called by the console or listed as knowingly unused with a reason. tenants was served by the gateway and answered by platform_tenant_summary() for weeks while nothing called it, so a real studio could sign up, be provisioned and use the app while the console showed only the worked example. Live subscribers are marked, namespaced and carry their real id, and are not given invented detail a real studio has none of.'],
  ['audit_channels.js',     'Sells via        ', 'A studio sets how each outlet sells - in person, online, or both - it survives a reload, it decides where a website order lands, and an outlet is never left selling through nothing. A branch cannot be saved without saying what it does, because stages, measurements and the word for an item all hang off that answer.'],
  ['audit_first_run.js',    'First run        ', 'A new studio is asked what it is called, what it does and how it sells, once, on its first live sign-in. Before this a tenant inherited DEFAULTS: a company called LAYI, one branch called Main, and bespoke+rtw from a fallback - somebody else’s label doing trades they are not in. The answers drive the production board, the visible tabs and the channels. Skipping is remembered so nobody is asked twice.'],
  ['audit_build_stamp.js',  'Build stamp     ', 'The app declares one release marker, shows it on the sign-in screen, and it equals the service worker cache name. A version that disagrees with the service worker is worse than none: it reports a fix as landed while the browser is still serving the build before it.'],
  ['audit_tenant_device.js','One device, one studio', 'A device records whose studio its data belongs to. Signing in as a different studio wipes what is local before hydrating, because hydrate only overwrites the keys the cloud returns and everything else would stay the last studio’s. An empty cloud is only seeded from a device that studio is claimed by — otherwise one studio’s orders are written into another’s business, with the right credentials, and the database stores them because nothing about them is wrong. No fallback to the demo tenant when an account has no business.'],
  ['audit_sync.js',        'Cloud-sync cover ', 'Every persisted data key must be wired to Supabase exactly once (relational pusher or app_state), and save() must stay a no-op offline.'],
  ['audit_webimport.js',  'Website import   ', 'Website orders map to the right studio record (retail / made-to-measure / consultation), money counts only when actually paid, and re-importing never duplicates.'],
  ['audit_moneyin.js',    'Money In hub     ', 'Every inflow is channel-tagged; a hand-logged payment is cash-received only (never double counts the accrual P&L); the hub is period + branch scoped and each channel figure reconciles with its drill-down.'],
  ['audit_paymethods.js', 'Payment methods  ', 'Every path that records money asks how it moved — cash, transfer, POS, card, a website sale — including the three biggest inflows, which never did: the deposit on an order, the balance on delivery and a shop sale. The list belongs to the studio and is editable, so Opay and Moniepoint sit alongside the defaults. Money with no method is counted as Not recorded rather than guessed at, the per-method totals reconcile with the overall totals, and cancelling the question cancels the payout rather than logging one nobody can reconcile.'],
  ['audit_simplicity.js', 'Progressive UI   ', 'A one-person shop hides the team & HR cluster (Team, Rota, Attendance, Leave, Company log, Payroll); it reveals automatically on hiring a 2nd teammate or adding a studio, and an explicit Settings toggle overrides. Hidden views redirect to the dashboard.'],
  ['audit_offline.js',    'Offline strength ', 'Offline reads as a feature: the connection pill stays hidden while online, appears with a "saved on this device" reassurance when the network drops, clears on reconnect, and the info modal explains nothing is lost.'],
  ['audit_print.js',      'Printable sheets ', 'Job sheet (work order + measurements), measurement sheet and stock list each generate branded, populated, branch-scoped printable HTML and are wired to a button in the UI. (Invoices/receipts already print.)'],
  ['audit_ownerpay.js',   'Owner pay        ', 'The owner can be paid five ways (% profit / % order value / fixed per order / fixed per outfit / monthly salary), set once globally and inherited by new orders; each basis computes correctly and stays capped to profit, and salary posts exactly one monthly cost.'],
  ['audit_notify.js',     'Notifications    ', 'The bell is a live activity feed: local sale/payment/status actions and (once live) other devices\' actions via realtime chime and drop in; a Settings panel controls sound, chime voice, volume, per-event toggles and pop-ups; Web Push stays scaffolded/dormant with SW handlers ready for go-live.'],
  ['audit_storage.js',    'Storage          ', 'Per-tenant storage is metered from image bytes only (text ignored), tiers set the limit (Free 1GB → Atelier 1TB), a Settings meter renders usage, and saveImageAsset() is the single pass-through seam that routes to cloud storage at go-live.'],
  ['audit_import.js',     'Import / migrate ', 'Six tolerant CSV importers (customers & measurements, orders, stock, staff, vendors, finances) match columns by alias so exports from other software line up; every importer is idempotent (matched records update, never duplicate); orders reuse the safe importWebOrders() path and keep the deposit as money paid; the migrate screen builds all six cards.'],
  ['audit_sort.js',       'List sorting     ', 'Six long lists share one sort control (name, newest, and each list own default); the choice is remembered per list; a brand-new client reaches the top instead of sinking to the bottom; Production stays unsortable because its order is its meaning.'],
  ['audit_planner.js',    'Planner          ', 'The planner READS the other sources rather than copying them: fittings stay appointments, deadlines stay orders, jobs stay tasks, and only meetings, reminders and content are its own. A studio must never end up with two records for one fitting. Repeats land on the right days and never before the start date, a free video room is unguessable, entries are scoped to their studio, and the Mine lens narrows to what is actually yours without hiding what belongs to the whole studio.'],
  ['audit_tiers.js',      'Plans & tiers    ', 'A plan gates SCALE — studios, seats, storage — plus exactly ONE declared capability: Basic sees who owes it and can invoice them, Pro sends the reminder. Never the production board, Finance or recording a payment, and never progressive disclosure, which must stay free so a studio is not charged at the moment it hires. The read-only half must genuinely be readable — Basic and Pro see the same names, the same money and the same overdue counts, and only the send button differs — because a "read-only" tier that hides the numbers is a hidden tier wearing a nicer word. Going over a limit hides nothing it already has; it only stops adding more, and says what more costs. Prices, names and seat counts must match the operator console, which is what actually bills.'],
  ['audit_media.js',      'Photos & offline ', 'Photos moved out of the database and into object storage, because base64 in Postgres cost 7.8x the right rate and, worse, made a studio\'s whole library re-read on every sign-in and re-broadcast on every order update — cost scaling as library x headcount on a plan that stopped limiting headcount. An upload that cannot happen (no signal, a refusal) keeps the bytes on the device and a sweep moves them up later; that same sweep is the migration for photos already in the database, so it runs constantly instead of once. The service worker half is the fiddly one: the bucket is private, so photos are fetched through SIGNED urls whose token changes every time one is minted — cached by full URL that is a miss every time, a cache that fills the disk and never answers, and photos that vanish offline. So the key is the object PATH with the query stripped. Also holds the 300MB bound and oldest-first eviction, refuses to cache an error response (which would break that photo permanently), and proves a shell release does NOT wipe the studio\'s offline photos. At 80% a calm notice; at 100% only uploads pause and orders, clients and finance are never touched.'],
  ['audit_history.js',    'Client history   ', 'Answers "what happened with this person?". Posts a real update through the same path the button uses and reads it back: a stage comment keeps who TYPED it and who did the WORK, which are different people whenever a CRE posts for a tailor. A delivered order stays in the client\'s history with its comments intact, because nothing archives and nothing may start filtering finished work out. Measurements record who held the tape and how — in the studio, over a video call, or numbers the client sent, which is flagged unverified on screen and on the printed sheet because it changes what a workroom should do before cutting. And Correspondence merges notes, order comments, measurements, payments and appointments while STORING none of them: delete a note at its source and it must vanish here, or the copy starts disagreeing with the record it came from.'],
  ['audit_marketing.js',  'Marketing        ', 'Marketing is made of what the studio already recorded rather than lists kept by hand: who bought what, who has not been seen in six months, and who ordered this time last year, which is the one that earns its keep because a tailor’s year repeats. A segment nobody can be reached in is never offered. Finished work with photos on it becomes a caption the studio can copy and a content entry in the calendar — and nothing posts on their behalf, because auto-posting means app review, expiring tokens and a breakage every few months.'],
  ['audit_feedback.js',   'Feedback channel ', 'A studio can send a suggestion, a feature request, a complaint or a support ticket from any screen and any role. It is written to the device BEFORE any attempt to send it, so bad signal never loses a message; anything undelivered stays queued, is shown as waiting, and goes on the next connection, exactly once. The console reads the inbox only through the admin-api gateway, never the table, and says whether it is showing real studios or the worked example.'],
  ['audit_paysetup.js',   'Pay setup        ', 'Allowances, pension and the pay lines a studio adds itself are all off until an owner switches them on, so a growing business still sees basic + commission = gross with no deductions section. Nothing is ever deducted without consent: a pension needs both the studio scheme and that person to be enrolled, and an opt-in line needs that person ticked. Take-home can never go below zero.'],
  ['audit_fabric.js',     'Fabric check     ', 'The order records WHOSE cloth it is, the work order says so in bold where the person cutting cannot miss it, and somebody is asked to check the cloth against the photo once work starts and before quality control. Studio stock can be replaced by walking to the shelf; a client’s own fabric cannot be replaced at any price, and it is the piece that gets mixed up.'],
  ['audit_trades.js',     'Multi-trade      ', 'Every trade the website sells to (bespoke, ready-to-wear, footwear, bags & leather, fabrics, haberdashery) can be selected, opens the right boards, and gets production stages, measurements and wording written in its own language. A shoemaker is never handed Fabric Received or asked for an Agbada arm-span, and a measurement already on file never disappears when a studio changes trade.'],
  ['audit_planner.js',    'Calendar         ', 'The calendar is a VIEW over what the studio already keeps, not a second set of records: booking a fitting from it creates an APPOINTMENT, so there is never a second copy to disagree with the first. It carries tasks, fittings, order deadlines, announcements, meetings, reminders and content; every meeting gets its own free video room that no other meeting shares; repeats land on the days they fall on and no others; and the Mine lens shows a person their own bench without hiding the studio’s own deadlines.'],
  ['audit_whatsapp.js',   'WhatsApp auto    ', 'The auto-WhatsApp seam exists and stays DORMANT until an endpoint is set and the app is live (today\'s manual hand-off is unchanged); milestone hooks fire on order-created and ready; the Settings panel explains the go-live requirement; and no WhatsApp API token ever ships in the client.'],
];

let failed = [];
console.log('Verifying: ' + app + '\n');
for (const [script, label, why] of GATES) {
  const p = path.join(here, script);
  if (!fs.existsSync(p)) { console.log('  SKIP  ' + label.trim() + ' (missing ' + script + ')'); continue; }
  try {
    const out = execFileSync('node', [p, app], { encoding: 'utf8', stdio: ['ignore','pipe','pipe'] });
    const last = out.trim().split('\n').filter(Boolean).pop() || 'ok';
    console.log('  PASS  ' + label + '  ' + last.trim());
  } catch (e) {
    failed.push(script);
    const out = ((e.stdout||'') + (e.stderr||'')).trim();
    console.log('  FAIL  ' + label);
    out.split('\n').slice(-12).forEach(l => console.log('        ' + l));
  }
}

console.log('');
if (failed.length) {
  console.log('=== ' + failed.length + ' GATE(S) FAILED: ' + failed.join(', ') + ' ===');
  console.log('Do not ship. Each gate above prints why it exists; fix the cause, not the test.');
  process.exit(1);
}
console.log('=== ALL GATES GREEN ===');
