-- =====================================================================
-- The Label Board — tenant isolation
--
-- The security boundary of the whole product. Every studio's data is
-- fenced off from every other studio's, and the fence is enforced by the
-- database rather than by application code, because application code can
-- be bypassed by anyone holding the anon key (which is public, by design).
--
-- Three ideas carry all the weight:
--
--   1. Every tenant row carries business_id, NOT NULL. No exceptions.
--   2. RLS is on and FORCED on every one of those tables, and the policy
--      derives the caller's business from their session, never from the
--      request. A client that can name its own business_id has no
--      isolation at all.
--   3. Composite foreign keys pin children to their parent's business, so
--      a row linking two tenants cannot be constructed even if a policy
--      is later written wrongly. Belt as well as braces.
--
-- The policies below are generated by a loop rather than written out by
-- hand. That is deliberate: hand-written policies are where this goes
-- wrong, because it only takes one table with a missing WITH CHECK for a
-- tenant to be able to stamp its rows with someone else's business_id.
-- A loop cannot forget a table or omit a clause.
--
-- Deliberately absent: any policy granting platform admins read access to
-- tenant data. The operator console needs cross-tenant reads, but doing
-- that through RLS would mean one compromised admin session, or one XSS
-- in the console, reads every studio on the platform straight from the
-- browser. Cross-tenant reads go through an Edge Function that checks
-- platform_admins server side and can log what it served. See
-- supabase/functions/admin-api.
--
-- Verified by supabase/tests/rls_harness.mjs, which attacks these policies
-- from the position of a signed-in tenant. Run it after any change here.
-- =====================================================================

-- gen_random_uuid() is core Postgres from 13 onward, so no pgcrypto needed.
create schema if not exists app;

-- Supabase ships these roles. Created here only when missing, so this file
-- also runs against a bare Postgres for testing.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end $$;

-- =====================================================================
-- TENANTS
-- =====================================================================

create table if not exists public.businesses (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  slug        text not null unique,
  plan        text not null default 'trial'
                check (plan in ('trial','starter','pro','premium')),
  status      text not null default 'active'
                check (status in ('active','suspended','closed')),
  created_at  timestamptz not null default now()
);

create table if not exists public.branches (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name        text not null,
  created_at  timestamptz not null default now(),
  -- FK target for children, so a child's branch and business must agree
  constraint branches_id_business_key unique (id, business_id)
);

-- Who may act for which business. This is the only source of truth for
-- access; nothing reads a business_id off the request.
create table if not exists public.memberships (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id     uuid not null,
  branch_id   uuid,                       -- null means every branch
  role        text not null default 'staff'
                check (role in ('owner','manager','staff','viewer')),
  status      text not null default 'active'
                check (status in ('active','invited','suspended')),
  created_at  timestamptz not null default now(),
  unique (business_id, user_id),
  constraint memberships_branch_in_business
    foreign key (branch_id, business_id)
    references public.branches(id, business_id) on delete restrict
);

-- Your own staff, for the operator console. Not a tenant table.
create table if not exists public.platform_admins (
  id     uuid primary key,
  email  text,
  added_at timestamptz not null default now()
);

-- =====================================================================
-- TENANT DATA
--
-- Every table: business_id NOT NULL, and unique (id, business_id) so that
-- children can be pinned to the same tenant by composite FK.
-- =====================================================================

create table if not exists public.customers (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id   uuid,
  name        text not null,
  phone       text,
  email       text,
  created_at  timestamptz not null default now(),
  constraint customers_id_business_key unique (id, business_id),
  constraint customers_branch_in_business
    foreign key (branch_id, business_id)
    references public.branches(id, business_id) on delete restrict
);

-- Business wide, not branch scoped: one catalogue across the studios.
create table if not exists public.products (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name        text not null,
  price       numeric(14,2) not null default 0,
  created_at  timestamptz not null default now(),
  constraint products_id_business_key unique (id, business_id)
);

create table if not exists public.orders (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id   uuid,
  customer_id uuid,
  ref         text not null,
  total       numeric(14,2) not null default 0,
  status      text not null default 'new',
  created_at  timestamptz not null default now(),
  constraint orders_id_business_key unique (id, business_id),
  constraint orders_branch_in_business
    foreign key (branch_id, business_id)
    references public.branches(id, business_id) on delete restrict,
  constraint orders_customer_in_business
    foreign key (customer_id, business_id)
    references public.customers(id, business_id) on delete restrict
);

-- The child table that leaks in most multi-tenant apps, because people
-- put a policy on orders and forget this one. It carries its own
-- business_id and is pinned to its order's tenant.
create table if not exists public.order_items (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  order_id    uuid not null,
  product_id  uuid,
  qty         integer not null default 1 check (qty > 0),
  price       numeric(14,2) not null default 0,
  constraint order_items_id_business_key unique (id, business_id),
  constraint order_items_order_in_business
    foreign key (order_id, business_id)
    references public.orders(id, business_id) on delete cascade,
  constraint order_items_product_in_business
    foreign key (product_id, business_id)
    references public.products(id, business_id) on delete restrict
);

create table if not exists public.transactions (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id   uuid,
  order_id    uuid,
  kind        text not null default 'sale' check (kind in ('sale','refund','expense')),
  amount      numeric(14,2) not null default 0,
  at          timestamptz not null default now(),
  constraint transactions_id_business_key unique (id, business_id),
  constraint transactions_branch_in_business
    foreign key (branch_id, business_id)
    references public.branches(id, business_id) on delete restrict,
  constraint transactions_order_in_business
    foreign key (order_id, business_id)
    references public.orders(id, business_id) on delete cascade
);

-- A studio's own employees. Distinct from memberships: not every employee
-- gets a login, and not every login is an employee.
create table if not exists public.staff (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id   uuid,
  user_id     uuid,
  name        text not null,
  job_title   text,
  basic       numeric(14,2) not null default 0,
  created_at  timestamptz not null default now(),
  constraint staff_id_business_key unique (id, business_id),
  constraint staff_branch_in_business
    foreign key (branch_id, business_id)
    references public.branches(id, business_id) on delete restrict
);

create table if not exists public.attendance (
  id          uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id   uuid,
  staff_id    uuid not null,
  on_at       timestamptz,
  off_at      timestamptz,
  constraint attendance_id_business_key unique (id, business_id),
  constraint attendance_branch_in_business
    foreign key (branch_id, business_id)
    references public.branches(id, business_id) on delete restrict,
  constraint attendance_staff_in_business
    foreign key (staff_id, business_id)
    references public.staff(id, business_id) on delete cascade
);

-- =====================================================================
-- SCOPE HELPERS
--
-- SECURITY DEFINER so the lookup against memberships is not itself
-- filtered by memberships' own RLS, which would either recurse or quietly
-- return nothing. search_path is pinned because a SECURITY DEFINER
-- function with a mutable search_path is a privilege escalation waiting
-- to happen.
-- =====================================================================

create or replace function app.in_scope(p_business uuid, p_branch uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.memberships m
    where m.user_id = auth.uid()
      and m.status = 'active'
      and m.business_id = p_business
      and (
        m.branch_id is null      -- member covers the whole business
        or p_branch is null      -- row belongs to the whole business
        or m.branch_id = p_branch
      )
  );
$$;

create or replace function app.is_business_admin(p_business uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.memberships m
    where m.user_id = auth.uid()
      and m.status = 'active'
      and m.business_id = p_business
      and m.role in ('owner','manager')
  );
$$;

create or replace function app.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.platform_admins pa where pa.id = auth.uid()
  );
$$;

revoke all on function app.in_scope(uuid, uuid) from public;
revoke all on function app.is_business_admin(uuid) from public;
revoke all on function app.is_platform_admin() from public;
grant execute on function app.in_scope(uuid, uuid) to authenticated, service_role;
grant execute on function app.is_business_admin(uuid) to authenticated, service_role;
grant execute on function app.is_platform_admin() to authenticated, service_role;
grant usage on schema app to authenticated, service_role;

-- =====================================================================
-- POLICIES ON THE TENANT TABLES
--
-- Generated, so that no table can be missed and no write policy can be
-- created without its WITH CHECK. A table with branch_id is scoped by
-- branch as well; one without is business wide.
-- =====================================================================

do $$
declare
  t           text;
  pred        text;
  has_branch  boolean;
  tenant_tables text[] := array[
    'customers','products','orders','order_items',
    'transactions','staff','attendance'
  ];
begin
  foreach t in array tenant_tables
  loop
    select exists (
      select 1 from information_schema.columns c
      where c.table_schema = 'public'
        and c.table_name   = t
        and c.column_name  = 'branch_id'
    ) into has_branch;

    pred := case when has_branch
                 then 'app.in_scope(business_id, branch_id)'
                 else 'app.in_scope(business_id, null)'
            end;

    execute format('alter table public.%I enable row level security', t);
    -- FORCE so the table owner is subject to policies too. service_role
    -- holds BYPASSRLS, so the admin gateway still works.
    execute format('alter table public.%I force row level security', t);

    execute format('create index if not exists %I on public.%I (business_id)',
                   'idx_' || t || '_business', t);

    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete', t);

    execute format('create policy %I on public.%I for select to authenticated using (%s)',
                   t || '_select', t, pred);
    execute format('create policy %I on public.%I for insert to authenticated with check (%s)',
                   t || '_insert', t, pred);
    -- USING gates which rows may be touched; WITH CHECK gates what they
    -- may become. Without the second, a tenant can move its own row into
    -- another tenant by rewriting business_id.
    execute format('create policy %I on public.%I for update to authenticated using (%s) with check (%s)',
                   t || '_update', t, pred, pred);
    execute format('create policy %I on public.%I for delete to authenticated using (%s)',
                   t || '_delete', t, pred);

    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;

-- =====================================================================
-- POLICIES ON THE TENANT SPINE
-- =====================================================================

alter table public.businesses  enable row level security;
alter table public.businesses  force  row level security;
alter table public.branches    enable row level security;
alter table public.branches    force  row level security;
alter table public.memberships enable row level security;
alter table public.memberships force  row level security;
alter table public.platform_admins enable row level security;
alter table public.platform_admins force  row level security;

-- A business is visible to its members and editable by its admins.
-- No INSERT or DELETE policy: creating and closing a business is a
-- signup/billing operation and belongs to the server, not the browser.
drop policy if exists businesses_select on public.businesses;
create policy businesses_select on public.businesses
  for select to authenticated using (app.in_scope(id, null));

drop policy if exists businesses_update on public.businesses;
create policy businesses_update on public.businesses
  for update to authenticated
  using (app.is_business_admin(id))
  with check (app.is_business_admin(id));

drop policy if exists branches_select on public.branches;
create policy branches_select on public.branches
  for select to authenticated using (app.in_scope(business_id, id));

drop policy if exists branches_insert on public.branches;
create policy branches_insert on public.branches
  for insert to authenticated with check (app.is_business_admin(business_id));

drop policy if exists branches_update on public.branches;
create policy branches_update on public.branches
  for update to authenticated
  using (app.is_business_admin(business_id))
  with check (app.is_business_admin(business_id));

drop policy if exists branches_delete on public.branches;
create policy branches_delete on public.branches
  for delete to authenticated using (app.is_business_admin(business_id));

-- You can always see your own membership; admins see the whole team.
drop policy if exists memberships_select on public.memberships;
create policy memberships_select on public.memberships
  for select to authenticated
  using (user_id = auth.uid() or app.is_business_admin(business_id));

drop policy if exists memberships_insert on public.memberships;
create policy memberships_insert on public.memberships
  for insert to authenticated with check (app.is_business_admin(business_id));

drop policy if exists memberships_update on public.memberships;
create policy memberships_update on public.memberships
  for update to authenticated
  using (app.is_business_admin(business_id))
  with check (app.is_business_admin(business_id));

drop policy if exists memberships_delete on public.memberships;
create policy memberships_delete on public.memberships
  for delete to authenticated using (app.is_business_admin(business_id));

-- platform_admins gets no policy at all. RLS is on, so it is unreadable
-- from any browser session; only the service role can see it.

create index if not exists idx_memberships_user on public.memberships(user_id);
create index if not exists idx_memberships_business on public.memberships(business_id);
create index if not exists idx_branches_business on public.branches(business_id);

revoke all on public.businesses, public.branches, public.memberships,
              public.platform_admins from anon;
grant select on public.businesses to authenticated;
grant update on public.businesses to authenticated;
grant select, insert, update, delete on public.branches to authenticated;
grant select, insert, update, delete on public.memberships to authenticated;

-- =====================================================================
-- VIEWS
--
-- security_invoker makes a view run as the caller. Without it a view runs
-- as its owner and hands back every tenant's rows, which is one of the
-- quietest ways to undo all of the above.
-- =====================================================================

create or replace view public.order_summary
with (security_invoker = true) as
  select o.business_id,
         o.branch_id,
         o.id,
         o.ref,
         o.total,
         count(i.id) as item_count
  from public.orders o
  left join public.order_items i
         on i.order_id = o.id
        and i.business_id = o.business_id
  group by o.business_id, o.branch_id, o.id, o.ref, o.total;

revoke all on public.order_summary from anon;
grant select on public.order_summary to authenticated;
